project_id = "pfmwtbyqjuadmukiuyjy"

[functions.redeem-code]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cleanup-orders]
verify_jwt = false
